#!/usr/bin/env sh
set -eu

# Usage:
#   sudo DOMAIN=turn-asia.chadchat.fun PUBLIC_IP=1.2.3.4 TURN_USERNAME=turnuser TURN_PASSWORD=turnpass ./scripts/setup-coturn.sh
#
# Optional:
#   REGION_NAME=asia
#   TURN_REALM=chadchat.fun
#   TURN_MIN_PORT=49152
#   TURN_MAX_PORT=65535
#   ENABLE_TLS=1
#   EMAIL=admin@chadchat.fun
#
# Notes:
# - Run on Ubuntu/Debian with a public IP.
# - DNS A record for DOMAIN must already point to PUBLIC_IP.
# - Ports that must be open in cloud firewall/security group:
#   3478/tcp, 3478/udp, 5349/tcp, TURN_MIN_PORT-TURN_MAX_PORT/udp

DOMAIN="${DOMAIN:-}"
PUBLIC_IP="${PUBLIC_IP:-}"
TURN_USERNAME="${TURN_USERNAME:-}"
TURN_PASSWORD="${TURN_PASSWORD:-}"
REGION_NAME="${REGION_NAME:-}"
TURN_REALM="${TURN_REALM:-chadchat.fun}"
TURN_MIN_PORT="${TURN_MIN_PORT:-49152}"
TURN_MAX_PORT="${TURN_MAX_PORT:-65535}"
ENABLE_TLS="${ENABLE_TLS:-1}"
EMAIL="${EMAIL:-}"

if [ -z "$DOMAIN" ] || [ -z "$PUBLIC_IP" ] || [ -z "$TURN_USERNAME" ] || [ -z "$TURN_PASSWORD" ]; then
  echo "Missing required env vars."
  echo "Required: DOMAIN, PUBLIC_IP, TURN_USERNAME, TURN_PASSWORD"
  exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root or with sudo."
  exit 1
fi

if [ -z "$REGION_NAME" ]; then
  REGION_NAME="$DOMAIN"
fi

echo "==> Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y coturn certbot

echo "==> Enabling coturn service flag"
if [ -f /etc/default/coturn ]; then
  sed -i 's/^#\?TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
fi

CERT_PATH=""
KEY_PATH=""

if [ "$ENABLE_TLS" = "1" ]; then
  if [ -z "$EMAIL" ]; then
    CERTBOT_EMAIL_FLAGS="--register-unsafely-without-email"
  else
    CERTBOT_EMAIL_FLAGS="--email $EMAIL"
  fi

  echo "==> Requesting Let's Encrypt certificate for $DOMAIN"
  systemctl stop coturn >/dev/null 2>&1 || true
  # shellcheck disable=SC2086
  certbot certonly --standalone --non-interactive --agree-tos $CERTBOT_EMAIL_FLAGS -d "$DOMAIN"

  CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
  KEY_PATH="/etc/letsencrypt/live/$DOMAIN/privkey.pem"
fi

echo "==> Writing coturn config"
cat >/etc/turnserver.conf <<EOF
# Generated by setup-coturn.sh
listening-port=3478
tls-listening-port=5349

listening-ip=${PUBLIC_IP}
external-ip=${PUBLIC_IP}

realm=${TURN_REALM}
server-name=${REGION_NAME}
fingerprint
lt-cred-mech
user=${TURN_USERNAME}:${TURN_PASSWORD}

min-port=${TURN_MIN_PORT}
max-port=${TURN_MAX_PORT}

no-loopback-peers
no-multicast-peers
stale-nonce
log-file=/var/log/turnserver.log
simple-log

# Keep UDP relay enabled. WebRTC depends on it for low latency.
no-tcp-relay
EOF

if [ "$ENABLE_TLS" = "1" ]; then
  cat >>/etc/turnserver.conf <<EOF
cert=${CERT_PATH}
pkey=${KEY_PATH}
EOF
fi

echo "==> Restarting coturn"
systemctl enable coturn
systemctl restart coturn
systemctl status coturn --no-pager || true

echo "==> Setup complete"
echo "Use these URLs in backend:"
echo "  turn:${DOMAIN}:3478"
if [ "$ENABLE_TLS" = "1" ]; then
  echo "  turns:${DOMAIN}:5349"
fi

echo
echo "Cloud firewall still needs these ports open:"
echo "  3478/tcp"
echo "  3478/udp"
if [ "$ENABLE_TLS" = "1" ]; then
  echo "  5349/tcp"
fi
echo "  ${TURN_MIN_PORT}-${TURN_MAX_PORT}/udp"
